FROM python:3.11-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PIP_NO_CACHE_DIR=1

RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.deploy.txt ./

RUN pip install --upgrade pip setuptools wheel
RUN pip install --index-url https://download.pytorch.org/whl/cpu torch
RUN grep -v '^torch' requirements.deploy.txt > requirements.deploy.no_torch.txt \
    && pip install -r requirements.deploy.no_torch.txt

RUN pip install playwright
RUN python -m playwright install --with-deps

RUN pip install playwright
RUN python -m playwright install --with-deps
RUN pip install playwright-stealth
RUN pip install peft

# for headless scraping
RUN apt-get update && apt-get install -y xvfb

COPY src ./src
COPY scripts ./scripts
COPY pyproject.toml README.md ./

EXPOSE 8501

CMD ["python", "scripts/run_ui.py"]